name: Release Code
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Run Packager
        run: | 
          cd ${{ gethub.workspace }}
          ls
          ./package
      - run: echo "üçè This job's status is ${{ job.status }}."
